name: Verify website spelling
on:
    push:
        paths:
            - docs/index.md
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: sudo npm install --global spellchecker-cli --save-dev
            - name: Check spelling
              run: ./node_modules/.bin/spellchecker docs/index.md -i Schoology Harker